# Generated by Django 6.0.4 on 2026-05-05 07:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('available', 'Available'), ('borrowed', 'Borrowed'), ('unavailable', 'Not Available')], default='available', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BorrowTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower_name', models.CharField(max_length=150)),
                ('purpose', models.TextField()),
                ('released_by', models.CharField(max_length=150)),
                ('date_borrowed', models.DateTimeField(default=django.utils.timezone.now)),
                ('expected_return', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('returned', 'Returned')], default='ongoing', max_length=20)),
                ('date_returned', models.DateTimeField(blank=True, null=True)),
                ('returned_by', models.CharField(blank=True, max_length=150)),
                ('received_by', models.CharField(blank=True, max_length=150)),
                ('return_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ems.department')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='ems.equipment')),
            ],
            options={
                'ordering': ['-date_borrowed'],
            },
        ),
    ]
