# Generated by Django 6.0.4 on 2026-05-11 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0002_department_equipment_borrowtransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowtransaction',
            name='department',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
