# Generated by Django 6.0.4 on 2026-05-11 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0003_alter_borrowtransaction_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowtransaction',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ems.department'),
        ),
    ]
