# Generated by Django 6.0.4 on 2026-05-11 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0004_alter_borrowtransaction_department'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Department',
            new_name='Division',
        ),
        migrations.RenameField(
            model_name='borrowtransaction',
            old_name='expected_return',
            new_name='due_date',
        ),
        migrations.RemoveField(
            model_name='borrowtransaction',
            name='department',
        ),
        migrations.AddField(
            model_name='borrowtransaction',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ems.division'),
        ),
    ]
