# Generated by Django 6.0.2 on 2026-05-12 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0005_rename_department_division_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowtransaction',
            name='transaction_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
