# Generated by Django 6.0.2 on 2026-05-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0006_borrowtransaction_transaction_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowtransaction',
            name='date_borrowed',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
